pipeline {
    agent any
    environment {
        BRANCH_NAME = "${env.BRANCH_NAME}"
    	ENV = BRANCH_NAME.toLowerCase()
   	    APP_NAME = "api-gateway" 
    	IMAGE_NAME = "shivanand1234/${APP_NAME}:${ENV}"
    	KUBECONFIG = "$HOME/.kube/config"  
    }
    tools {
        maven 'Maven-3.8.1'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
        }
        stage('Build with Maven') {
            steps {
                    sh 'mvn clean install -DskipTests'
            }
        }
        stage('Docker Build') {
            steps {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: "${KUBECONFIG_CREDENTIAL_ID}", variable: 'KUBECONFIG_FILE')]) {
                    sh '''
                        export KUBECONFIG=$KUBECONFIG_FILE
                        kubectl apply -f ${JOB_BASE_NAME}/k8s/deployment.yaml
                        kubectl apply -f ${JOB_BASE_NAME}/k8s/service.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ deployed successfully!"
        }
        failure {
            echo "❌ deployment failed ."
        }
    }
}