pipeline {
    agent any

    environment {
        BRANCH_NAME = "${env.BRANCH_NAME}"
        ENV = "${BRANCH_NAME.toLowerCase()}"
        APP_NAME = "api-gateway"
        VERSION_TAG = "${env.BUILD_NUMBER}"
        IMAGE_NAME = "shivanand1234/${APP_NAME}:v${VERSION_TAG}"
        KUBECONFIG = "$HOME/.kube/config"
    }

    tools {
        maven 'Maven-3.8.1'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build with Maven') {
            steps {
                sh '''
                export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
                export PATH=$JAVA_HOME/bin:$PATH
                java -version
                mvn -version
                mvn clean install -DskipTests
            '''
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-cred-id', variable: 'KUBECONFIG_FILE')]) {
                    sh '''
                        export KUBECONFIG=$KUBECONFIG_FILE
                        kubectl apply -f k8s/deployment.yaml
                        kubectl apply -f k8s/service.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployed $APP_NAME successfully to $ENV!"
        }
        failure {
            echo "❌ Deployment of $APP_NAME to $ENV failed."
        }
    }
}
