apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  templete:
    metedata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointmet-service:latest
        ports:
        - containerPort: 8060