apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app:  authentication-service
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
  type: ClusterIP
