apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-webapp
  namespace: digiDoc-dev
  labels:
    app: product-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-webapp
  template:
    metadata:
      labels:
        app: product-webapp
    spec:
      containers:
      - name: product-webapp
        image: product-webapp:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"