apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-webapp
  templete:
    metadata:
      labels:
        app: product-webapp
    spec:
      containers:
      - name: product-webapp
        image: product-webapp:latest
        ports:
        - containerPort: 3000