apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: digiDoc-dev
  labels:
    app: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP