apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: digiDoc-dev
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672