apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: digiDoc-dev
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "root"
        - name: RABBITMQ_DEFAULT_PASS
          value: "root123"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"