apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  templete:
    matadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: authentiocation-service:latest
        ports:
        - containerPort: 8095