apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: digiDoc-dev
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: authentiocation-service:latest
          ports:
            - containerPort: 8095
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"