apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: digiDoc-dev
  labels: 
    app: authentication-service
spec:
  selector:
    app:  authentication-service
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP
